version: "3.7"

services:
  postgres:
    hostname: postgres
    image: sharp6292/postgres:latest

    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${POSTPASS:?err}
      SHARPDOMAINS: ${SHARPDOMAINS:?err}

    volumes:
       - postgres:/data/postgres

    restart: always

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL:?err}
      PGADMIN_DEFAULT_PASSWORD: ${ADMINPASS:?err}
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 5

    volumes:
       - pgadmin:/root/.pgadmin

    restart: always

volumes:
  postgres:
  pgadmin:

networks:
    default:
        external:
            name: sharpnet
