version: 2.1

orbs:
  docker: sharptools/docker@volatile
  sharpcd: sharptools/sharpcd@volatile

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - sharpcd/install

      - run:
          name: "Setup Env"
          command: |
            echo "ADMIN_EMAIL=${ADMIN_EMAIL}" > .env
            echo "ADMINPASS=${ADMINPASS}" >> .env
            echo "POSTPASS=${POSTPASS}" >> .env
            echo "SHARPDOMAINS=${SHARPDOMAINS}" >> .env

      - sharpcd/deploy

workflows:
  version: 2
  workflow:
    jobs:
      - docker/build:
          context: General
          image: sharp6292/postgres:latest


      - deploy:
          context: General
          requires:
            - docker/build

          filters:
            branches:
              only: main